language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

branches: # build only on these branches
  only:
    - master

notifications:
    webhooks: https://oapi.dingtalk.com/robot/send?access_token=096ed387df243a6d60835aadeccc47165f3813bc7cb81cdd0cfeadfd28e3acc1
    email: false
    on_success: change
    on_failure: always

script:
  - export GO111MODULE=on
  - go mod tidy
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./credentials/...
  - test -z $SUB_ALICLOUD_ACCESS_KEY -a -z $SUB_ALICLOUD_SECRET_KEY || go test -v -timeout 120s ./integration/...

after_success:
  - bash <(curl -s https://codecov.io/bash)